/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Emmanuel
 */
public class Causas extends javax.swing.JFrame {

    /**
     * Creates new form Causas
     */
    public Causas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiulo = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        causa1 = new javax.swing.JLabel();
        causa1p2 = new javax.swing.JLabel();
        gases = new javax.swing.JButton();
        causa2 = new javax.swing.JLabel();
        quema = new javax.swing.JButton();
        causa3 = new javax.swing.JLabel();
        causa4 = new javax.swing.JLabel();
        causa5 = new javax.swing.JLabel();
        deforesta = new javax.swing.JButton();
        exceso = new javax.swing.JButton();
        alta = new javax.swing.JButton();
        Charizard = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 499));
        setMinimumSize(new java.awt.Dimension(810, 509));
        setResizable(false);
        getContentPane().setLayout(null);

        tiulo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        tiulo.setForeground(new java.awt.Color(255, 255, 255));
        tiulo.setText("Causas");
        getContentPane().add(tiulo);
        tiulo.setBounds(330, 20, 140, 30);

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(600, 420, 110, 40);

        texto1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.setText("En este apartado se mostrarán las 5 ");
        getContentPane().add(texto1);
        texto1.setBounds(20, 60, 300, 40);

        texto2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto2.setText("principales causas del calenta");
        getContentPane().add(texto2);
        texto2.setBounds(310, 60, 240, 40);

        texto3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 255, 255));
        texto3.setText("miento Global");
        getContentPane().add(texto3);
        texto3.setBounds(550, 60, 110, 40);

        causa1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        causa1.setForeground(new java.awt.Color(255, 255, 255));
        causa1.setText("1.Aumento de los gases");
        getContentPane().add(causa1);
        causa1.setBounds(20, 110, 200, 20);

        causa1p2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        causa1p2.setText("de efecto invernadero");
        getContentPane().add(causa1p2);
        causa1p2.setBounds(220, 110, 190, 20);

        gases.setText("Más información");
        gases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasesActionPerformed(evt);
            }
        });
        getContentPane().add(gases);
        gases.setBounds(20, 140, 120, 30);

        causa2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        causa2.setForeground(new java.awt.Color(255, 255, 255));
        causa2.setText("2.Quema de combustibles fósiles");
        getContentPane().add(causa2);
        causa2.setBounds(20, 180, 270, 30);

        quema.setText("Más información");
        quema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quemaActionPerformed(evt);
            }
        });
        getContentPane().add(quema);
        quema.setBounds(20, 220, 110, 30);

        causa3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        causa3.setForeground(new java.awt.Color(255, 255, 255));
        causa3.setText("3.Deforestación selva y bosques");
        getContentPane().add(causa3);
        causa3.setBounds(20, 260, 270, 30);

        causa4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        causa4.setForeground(new java.awt.Color(255, 255, 255));
        causa4.setText("4.Excesivo uso  de fertilizantes");
        getContentPane().add(causa4);
        causa4.setBounds(10, 330, 250, 30);

        causa5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        causa5.setForeground(new java.awt.Color(255, 255, 255));
        causa5.setText("5.Alta producción de residuos");
        getContentPane().add(causa5);
        causa5.setBounds(290, 330, 240, 30);

        deforesta.setText("Más información");
        deforesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deforestaActionPerformed(evt);
            }
        });
        getContentPane().add(deforesta);
        deforesta.setBounds(20, 290, 109, 30);

        exceso.setText("Más información");
        exceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excesoActionPerformed(evt);
            }
        });
        getContentPane().add(exceso);
        exceso.setBounds(20, 360, 120, 30);

        alta.setText("Más información");
        alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActionPerformed(evt);
            }
        });
        getContentPane().add(alta);
        alta.setBounds(360, 370, 110, 30);

        Charizard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/charizard.png"))); // NOI18N
        getContentPane().add(Charizard);
        Charizard.setBounds(670, 290, 100, 110);

        Fondo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calentamiento3.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasesActionPerformed
        // TODO add your handling code here:
        Gases gas=new Gases();
        gas.setVisible(true);
        gas.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_gasesActionPerformed

    private void quemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quemaActionPerformed
        // TODO add your handling code here:
        Quema que=new Quema();
        que.setVisible(true);;
        que.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_quemaActionPerformed

    private void deforestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deforestaActionPerformed
        // TODO add your handling code here:
        Ambiente amb=new Ambiente();
        amb.setVisible(true);
        amb.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_deforestaActionPerformed

    private void excesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excesoActionPerformed
        // TODO add your handling code here:
        Fertilizante fer=new Fertilizante();
        fer.setVisible(true);
        fer.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_excesoActionPerformed

    private void altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActionPerformed
        // TODO add your handling code here:
        Residuo res=new Residuo();
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_altaActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        Indice indice=new Indice();
        indice.setVisible(true);
        indice.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Causas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Causas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Causas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Causas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Causas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Charizard;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton alta;
    private javax.swing.JLabel causa1;
    private javax.swing.JLabel causa1p2;
    private javax.swing.JLabel causa2;
    private javax.swing.JLabel causa3;
    private javax.swing.JLabel causa4;
    private javax.swing.JLabel causa5;
    private javax.swing.JButton deforesta;
    private javax.swing.JButton exceso;
    private javax.swing.JButton gases;
    private javax.swing.JButton quema;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel tiulo;
    // End of variables declaration//GEN-END:variables
}
