/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Emmanuel
 */
public class Consiste extends javax.swing.JFrame {

    /**
     * Creates new form Consiste
     */
    public Consiste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        texto7 = new javax.swing.JLabel();
        Texto8 = new javax.swing.JLabel();
        texto9 = new javax.swing.JLabel();
        texto10 = new javax.swing.JLabel();
        texto11 = new javax.swing.JLabel();
        texto12 = new javax.swing.JLabel();
        texto13 = new javax.swing.JLabel();
        Charizard = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 427));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 427));
        setResizable(false);
        getContentPane().setLayout(null);

        titulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("¿En qué consiste?");
        getContentPane().add(titulo);
        titulo.setBounds(310, 10, 149, 22);

        regresar.setText("Regersar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(500, 350, 90, 30);

        texto1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(255, 255, 255));
        texto1.setText("Consiste en un aumento lento pero gradual de las temperaturas atmosféricas y oceánicas. ");
        getContentPane().add(texto1);
        texto1.setBounds(10, 50, 730, 20);

        texto2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto2.setForeground(new java.awt.Color(255, 255, 255));
        texto2.setText("La importancia de este fenómeno radica en que implica que las condiciones");
        getContentPane().add(texto2);
        texto2.setBounds(10, 80, 610, 30);

        texto3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 255, 255));
        texto3.setText("climáticas en las distintas regiones han sufrido cambios importantes,");
        getContentPane().add(texto3);
        texto3.setBounds(10, 110, 544, 22);

        texto4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(255, 255, 255));
        texto4.setText("que pueden afectar el desarrollo social, las condiciones de vida, la economía, etc.");
        getContentPane().add(texto4);
        texto4.setBounds(10, 130, 660, 22);

        texto5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto5.setForeground(new java.awt.Color(255, 255, 255));
        texto5.setText("La tierra ha pasado por diferentes procesos para ara cambiar su temperatura en su larga historia,");
        getContentPane().add(texto5);
        texto5.setBounds(10, 160, 780, 20);

        texto6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto6.setForeground(new java.awt.Color(255, 255, 255));
        texto6.setText("pero son naturales. Por el contrario, en la actualidad, los cambios experimentados son provocados");
        getContentPane().add(texto6);
        texto6.setBounds(10, 180, 790, 20);

        texto7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto7.setForeground(new java.awt.Color(255, 255, 255));
        texto7.setText("por manos humanas y trabajan en un tiempo relativamente limitado.");
        getContentPane().add(texto7);
        texto7.setBounds(10, 200, 550, 22);

        Texto8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Texto8.setForeground(new java.awt.Color(255, 255, 255));
        Texto8.setText("La liberación de gas metano a lo largo del globo, particularmente en la tundra ártica y los pantanos,");
        getContentPane().add(Texto8);
        Texto8.setBounds(10, 230, 790, 22);

        texto9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto9.setForeground(new java.awt.Color(255, 255, 255));
        texto9.setText("es originada por la naturaleza. Lo que comúnmente se conoce como “efecto invernadero”,");
        getContentPane().add(texto9);
        texto9.setBounds(10, 250, 720, 22);

        texto10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto10.setForeground(new java.awt.Color(255, 255, 255));
        texto10.setText("es precisamente el calentamiento que se produce cuando estos gases retienen el calor, dejando");
        getContentPane().add(texto10);
        texto10.setBounds(10, 270, 790, 22);

        texto11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto11.setForeground(new java.awt.Color(255, 255, 255));
        texto11.setText("pasar la luz (del mismo modo que lo hace un invernadero).");
        getContentPane().add(texto11);
        texto11.setBounds(10, 290, 470, 22);

        texto12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto12.setForeground(new java.awt.Color(255, 255, 255));
        texto12.setText("Es este mismo esfecto lo que provocan las emisiones de CO2,producto de las quemas de");
        getContentPane().add(texto12);
        texto12.setBounds(10, 320, 720, 22);

        texto13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto13.setForeground(new java.awt.Color(255, 255, 255));
        texto13.setText(" combustibles fósiles, provocados por los humanos.");
        getContentPane().add(texto13);
        texto13.setBounds(10, 350, 420, 22);

        Charizard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/charizard.png"))); // NOI18N
        getContentPane().add(Charizard);
        Charizard.setBounds(690, 60, 100, 110);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Espacio.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 800, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        Indice indice=new Indice();
        indice.setVisible(true);
        indice.setLocationRelativeTo(null);
        this.setVisible(false);        
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consiste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Charizard;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Texto8;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto10;
    private javax.swing.JLabel texto11;
    private javax.swing.JLabel texto12;
    private javax.swing.JLabel texto13;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto9;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
