/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Emmanuel
 */
public class Creditos extends javax.swing.JFrame {

    /**
     * Creates new form Creditos
     */
    public Creditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        Mejía = new javax.swing.JLabel();
        Alegría = new javax.swing.JLabel();
        Venegas = new javax.swing.JLabel();
        charizard = new javax.swing.JLabel();
        inves = new javax.swing.JLabel();
        prog = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        Venegas1 = new javax.swing.JLabel();
        Alegria1 = new javax.swing.JLabel();
        Mejía1 = new javax.swing.JLabel();
        Alegría2 = new javax.swing.JLabel();
        Mejía2 = new javax.swing.JLabel();
        Alegría3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 563));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1000, 563));
        setPreferredSize(new java.awt.Dimension(1000, 563));
        getContentPane().setLayout(null);

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(870, 440, 110, 50);

        titulo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        titulo.setText("Creado por:");
        getContentPane().add(titulo);
        titulo.setBounds(400, 0, 224, 40);

        Mejía.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Mejía.setText("Mejía Castañeda Bryan Emmanuel");
        getContentPane().add(Mejía);
        Mejía.setBounds(260, 80, 510, 50);

        Alegría.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Alegría.setText("Allegría García Fernando");
        getContentPane().add(Alegría);
        Alegría.setBounds(330, 40, 380, 50);

        Venegas.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Venegas.setText("Venegas Neria Kevin Yunuel");
        getContentPane().add(Venegas);
        Venegas.setBounds(330, 130, 390, 20);

        charizard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/charizard.png"))); // NOI18N
        getContentPane().add(charizard);
        charizard.setBounds(890, 20, 100, 110);

        inves.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        inves.setText("Investigación:");
        getContentPane().add(inves);
        inves.setBounds(400, 150, 270, 50);

        prog.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        prog.setForeground(new java.awt.Color(255, 255, 255));
        prog.setText("Programación:");
        getContentPane().add(prog);
        prog.setBounds(420, 390, 300, 50);

        dis.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setText("Diseño:");
        getContentPane().add(dis);
        dis.setBounds(470, 270, 160, 50);

        Venegas1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Venegas1.setText("Venegas Neria Kevin Yunuel");
        getContentPane().add(Venegas1);
        Venegas1.setBounds(350, 210, 390, 30);

        Alegria1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Alegria1.setText("Alegría García Fernando");
        getContentPane().add(Alegria1);
        Alegria1.setBounds(350, 240, 345, 34);

        Mejía1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Mejía1.setForeground(new java.awt.Color(255, 255, 255));
        Mejía1.setText("Mejía Castañeda Bryan Emmanuel");
        getContentPane().add(Mejía1);
        Mejía1.setBounds(310, 320, 490, 30);

        Alegría2.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Alegría2.setForeground(new java.awt.Color(255, 255, 255));
        Alegría2.setText("Alegría García Fernando");
        getContentPane().add(Alegría2);
        Alegría2.setBounds(380, 354, 360, 40);

        Mejía2.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Mejía2.setForeground(new java.awt.Color(255, 255, 255));
        Mejía2.setText("Mejía Castañeda Bryan Emmanuel");
        getContentPane().add(Mejía2);
        Mejía2.setBounds(340, 440, 490, 30);

        Alegría3.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        Alegría3.setForeground(new java.awt.Color(255, 255, 255));
        Alegría3.setText("Alegría García Fernando");
        getContentPane().add(Alegría3);
        Alegría3.setBounds(400, 470, 370, 50);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minecraft shader.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 1000, 563);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        Indice in=new Indice();
        in.setVisible(true);
        in.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alegria1;
    private javax.swing.JLabel Alegría;
    private javax.swing.JLabel Alegría2;
    private javax.swing.JLabel Alegría3;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Mejía;
    private javax.swing.JLabel Mejía1;
    private javax.swing.JLabel Mejía2;
    private javax.swing.JLabel Venegas;
    private javax.swing.JLabel Venegas1;
    private javax.swing.JLabel charizard;
    private javax.swing.JLabel dis;
    private javax.swing.JLabel inves;
    private javax.swing.JLabel prog;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
