/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Emmanuel
 */
public class Indice extends javax.swing.JFrame {

    /**
     * Creates new form Indice
     */
    public Indice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        definicion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        efectos = new javax.swing.JButton();
        causas = new javax.swing.JButton();
        creditos = new javax.swing.JButton();
        consiste = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        def = new javax.swing.JLabel();
        cons = new javax.swing.JLabel();
        caus = new javax.swing.JLabel();
        efec = new javax.swing.JLabel();
        cred = new javax.swing.JLabel();
        Charizard = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 419));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 419));
        setPreferredSize(new java.awt.Dimension(800, 419));
        setResizable(false);
        getContentPane().setLayout(null);

        definicion.setText("Definición");
        definicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definicionActionPerformed(evt);
            }
        });
        getContentPane().add(definicion);
        definicion.setBounds(30, 50, 90, 30);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(310, 340, 90, 40);

        efectos.setText("Efectos");
        efectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectosActionPerformed(evt);
            }
        });
        getContentPane().add(efectos);
        efectos.setBounds(420, 190, 80, 40);

        causas.setText("Causas");
        causas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                causasActionPerformed(evt);
            }
        });
        getContentPane().add(causas);
        causas.setBounds(320, 140, 100, 40);

        creditos.setText("Creditos");
        creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosActionPerformed(evt);
            }
        });
        getContentPane().add(creditos);
        creditos.setBounds(510, 270, 90, 40);

        consiste.setText("Consiste");
        consiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consisteActionPerformed(evt);
            }
        });
        getContentPane().add(consiste);
        consiste.setBounds(210, 90, 110, 40);

        titulo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        titulo.setText("Índice");
        getContentPane().add(titulo);
        titulo.setBounds(350, 0, 90, 33);

        def.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        def.setText("Definición de calenteamiento global ");
        getContentPane().add(def);
        def.setBounds(0, 20, 680, 34);

        cons.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        cons.setText("¿En qué consiste?");
        getContentPane().add(cons);
        cons.setBounds(120, 60, 240, 34);

        caus.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        caus.setText("Causas");
        getContentPane().add(caus);
        caus.setBounds(320, 110, 94, 34);

        efec.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        efec.setText("Efectos");
        getContentPane().add(efec);
        efec.setBounds(420, 160, 89, 34);

        cred.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        cred.setText("Creditos");
        getContentPane().add(cred);
        cred.setBounds(500, 230, 140, 34);

        Charizard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/charizard.png"))); // NOI18N
        getContentPane().add(Charizard);
        Charizard.setBounds(670, 290, 100, 110);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calentamiento2.jpg"))); // NOI18N
        Fondo.setText("1");
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 800, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void definicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definicionActionPerformed
        // TODO add your handling code here:
        Inicio inicio=new Inicio();
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_definicionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void causasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_causasActionPerformed
        // TODO add your handling code here:
        Causas cau=new Causas();
        cau.setVisible(true);
        cau.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_causasActionPerformed

    private void consisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consisteActionPerformed
        // TODO add your handling code here:
        Consiste con=new Consiste();
        con.setVisible(true);
        con.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_consisteActionPerformed

    private void creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosActionPerformed
        // TODO add your handling code here:
        Creditos cre=new Creditos();
        cre.setVisible(true);
        cre.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_creditosActionPerformed

    private void efectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectosActionPerformed
        // TODO add your handling code here:
        Efectos efec=new Efectos();
        efec.setVisible(true);
        efec.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_efectosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Indice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Charizard;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel caus;
    private javax.swing.JButton causas;
    private javax.swing.JLabel cons;
    private javax.swing.JButton consiste;
    private javax.swing.JLabel cred;
    private javax.swing.JButton creditos;
    private javax.swing.JLabel def;
    private javax.swing.JButton definicion;
    private javax.swing.JLabel efec;
    private javax.swing.JButton efectos;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
