/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Emmanuel
 */
public class Residuo extends javax.swing.JFrame {

    /**
     * Creates new form Residuo
     */
    public Residuo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regesar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qTexto = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 394));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 394));
        setPreferredSize(new java.awt.Dimension(800, 394));
        setResizable(false);
        getContentPane().setLayout(null);

        regesar.setText("Regresar");
        regesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regesarActionPerformed(evt);
            }
        });
        getContentPane().add(regesar);
        regesar.setBounds(623, 323, 90, 30);

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setText("Alta producción de residuos");
        getContentPane().add(titulo);
        titulo.setBounds(160, 20, 440, 50);

        qTexto.setColumns(20);
        qTexto.setRows(5);
        qTexto.setText("La alta producción de residuos también favorece el \ncalentamiento global. ¿De qué manera? \nCuantos más residuos produzcamos a diario,\nmayores serán los niveles de gas metano en el ambiente, \nun elemento que se genera durante la\ndescomposición de materiales en los vertederos\nAdemás, consumir de forma masiva supone una mayor demanda\ncon lo cual las industrias aumentarán sus\nniveles de producción y, por ende,los niveles de \ngases de efecto invernadero\nliberados a la atmósfera serán mayores.");
        jScrollPane1.setViewportView(qTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 110, 690, 210);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/residuos.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regesarActionPerformed
       // TODO add your handling code here:
       Causas cau=new Causas();
       cau.setVisible(true);
       cau.setLocationRelativeTo(null);
       this.setVisible(false);
    }//GEN-LAST:event_regesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Residuo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Residuo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Residuo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Residuo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Residuo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea qTexto;
    private javax.swing.JButton regesar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
